version: 0.2
env:
  variables:
    REPOSITORY_URI:018329519556.dkr.ecr.us-east-1.amazonaws.com/nestjs-quote
phases:
 install:
   runtime-versions:
     docker: 18
 pre_build:
   commands:
     - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
    #  - REPOSITORY_URI=${018329519556.dkr.ecr.us-east-1.amazonaws.com/nestjs-quote}
     - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
     - IMAGE_TAG=${COMMIT_HASH:=latest}
 build:
   commands:
     - docker build -t $REPOSITORY_URI:latest -f Dockerfile .
     - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
 post_build:
   commands:
     - docker push $REPOSITORY_URI:latest
     - docker push $REPOSITORY_URI:$IMAGE_TAG
     - printf '[{"name":"nestjs-quote","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
 files: imagedefinitions.json
